Repository YourFavoriteMusicDealer/web, pull requests merged in 2018-05, with the labels that each got.

#7 Bem
  src/App.vue
  src/assets/fonts/.gitkeep
  src/assets/img/.gitkeep
  src/main.js
Labels: enhancement

#10 :art: fix style
  src/App.vue
  src/main.js
Labels: invalid

#11 :bug: #8 fix volume width
  src/App.vue
Labels: bug

#13 :bug: close #9 Изменил стиль для имени артиста и композиции
  src/App.vue
Labels: bug

#16 :bug: #15 Поменял местами Название композиции и исполнителя
  src/App.vue
Labels: bug

#14 :sparkles: #6 Временная строка инпутом с визуализацией ее в браузерах
  src/App.vue
Labels: enhancement

#20 #18 Исправил время
  src/App.vue
Labels: bug

#19 Audio player
  src/App.vue
  src/assets/img/pause.svg
Labels: enhancement

#24 Обновил стиль плеера
  package.json
  src/App.vue
  src/assets/img/cover.jpg
  src/assets/img/cover.png
  src/assets/img/less-volume.svg
  src/assets/img/more-volume.svg
  src/assets/img/next.svg
  src/assets/img/pause.svg
  src/assets/img/play.svg
  src/assets/img/previous.svg
  src/main.js
  src/svg/download.svg
  src/svg/less-volume.svg
  src/svg/more-volume.svg
  src/svg/next.svg
  src/svg/pause.svg
  src/svg/play.svg
  src/svg/previous.svg
Labels: enhancement

#26 Fix buttons
  src/App.vue
Labels: bug

#29 Styду slider
  src/App.vue
Labels: invalid

#30 Minutes hours
  src/App.vue
Labels: invalid
